# Generated by Django 4.1.2 on 2022-11-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('author', models.CharField(max_length=50, verbose_name='Автор')),
                ('price', models.CharField(max_length=7, verbose_name='Цена')),
                ('data', models.IntegerField(max_length=4, verbose_name='Год написания')),
            ],
        ),
    ]
